/*
	File: fn_varHandle.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master handler for getting a variables name, short name, etc.
*/
private["_var","_mode"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
_mode = [_this,1,-1,[0]] call BIS_fnc_param;
if(_var == "" OR _mode == -1) exitWith {""};

switch (_mode) do
{
	case 0:
	{
		switch (_var) do
		{
			case "oilu": {"life_inv_oilu"};
			case "oilp": {"life_inv_oilp"};
			case "heroinu": {"life_inv_heroinu"};
			case "heroinp": {"life_inv_heroinp"};
			case "cannabis": {"life_inv_cannabis"};
			case "marijuana": {"life_inv_marijuana"};
			case "apple": {"life_inv_apple"};
			case "water": {"life_inv_water"};
			case "rabbit": {"life_inv_rabbit"};
			case "salema": {"life_inv_salema"};
			case "ornate": {"life_inv_ornate"};
			case "mackerel": {"life_inv_mackerel"};
			case "tuna": {"life_inv_tuna"};
			case "mullet": {"life_inv_mullet"};
			case "catshark": {"life_inv_catshark"};
			case "turtle": {"life_inv_turtle"};
			case "fishing": {"life_inv_fishingpoles"};
			case "coffee": {"life_inv_coffee"};
			case "turtlesoup": {"life_inv_turtlesoup"};
			case "donuts": {"life_inv_donuts"};
			case "fuelE": {"life_inv_fuelE"};
			case "fuelF": {"life_inv_fuelF"};
			case "money": {"life_cash"};
			case "pickaxe": {"life_inv_pickaxe"};
			case "copperore": {"life_inv_copperore"};
			case "ironore": {"life_inv_ironore"};
			case "iron_r": {"life_inv_ironr"};
			case "copper_r": {"life_inv_copperr"};
			case "salt": {"life_inv_salt"};
			case "salt_r": {"life_inv_saltr"};
			case "sand": {"life_inv_sand"};
			case "glass": {"life_inv_glass"};
			case "tbacon": {"life_inv_tbacon"};
			case "lockpick": {"life_inv_lockpick"};
			case "redgull": {"life_inv_redgull"};
			case "peach": {"life_inv_peach"};
			case "diamond": {"life_inv_diamond"};
			case "diamondc": {"life_inv_diamondr"};
			case "coke": {"life_inv_coke"};
			case "cokep": {"life_inv_cokep"};
			case "spikeStrip": {"life_inv_spikeStrip"};
			case "cement": {"life_inv_cement"};
			case "rock": {"life_inv_rock"};
			case "goldbar": {"life_inv_goldbar"};
			case "blastingcharge": {"life_inv_blastingcharge"};
			case "boltcutter": {"life_inv_boltcutter"};
			case "defusekit": {"life_inv_defusekit"};
			case "storagesmall": {"life_inv_storagesmall"};
			case "storagebig": {"life_inv_storagebig"};
			case "battery": {"life_inv_battery"};
			case "barrier": {"life_inv_barrier"};
			case "mauer": {"life_inv_mauer"};
			case "vehiclecharge": {"life_inv_vehiclecharge"};
			case "zipties": {"life_inv_zipties"};
			case "pizza": {"life_inv_pizza"};
			case "bandage": {"life_inv_bandage"};
			case "target": {"life_inv_target"};
			case "bottledbeer": {"life_inv_bottledbeer"};
			case "bottledwhiskey": {"life_inv_bottledwhiskey"};
			case "beer": {"life_inv_beer"};
			case "whiskey": {"life_inv_whiskey"};
			case "stretcher": {"life_inv_stretcher"};
			case "frogs": {"life_inv_frogs"};
			case "lsd": {"life_inv_lsd"};
			case "bigmac": {"life_inv_bigmac"};
			case "fries": {"life_inv_fries"};
			case "blindfold": {"life_inv_blindfold"};
			case "scissors": {"life_inv_scissors"};
			case "spraypaintcamo": {"life_inv_spraypaintcamo"};
			case "spraypaintfunky": {"life_inv_spraypaintfunky"};
			case "spraypaintpink": {"life_inv_spraypaintpink"};
			case "nos": {"life_inv_nos"};
			case "spraypaintzebra": {"life_inv_spraypaintzebra"};
			case "spraypaintcamo2": {"life_inv_spraypaintcamo2"};
			case "turbo": {"life_inv_turbo"};
			case "mp3player": {"life_inv_mp3player"};
			case "autorepairkit": {"life_inv_autorepairkit"};
			case "speedbomb": {"life_inv_speedbomb"};
			case "defibrillator": {"life_inv_defibrillator"};
			case "bullettcamera": {"life_inv_bullettcamera"};
			case "jailpass": {"life_inv_jailpass"};
			case "kidney": {"life_inv_kidney"};
			case "mdma": {"life_inv_mdma"};
			case "ecstasy": {"life_inv_ecstasy"};
			case "masterkey": {"life_inv_masterkey"};
			case "morphine": {"life_inv_morphine"};
			case "epipen": {"life_inv_epipen"};
			case "antifreeze": {"life_inv_antifreeze"};
			case "jailblueprint": {"life_inv_jailblueprint"};
			case "keycard": {"life_inv_keycard"};
		};
	};
	
	case 1:
	{
		switch (_var) do
		{
			case "life_inv_oilu": {"oilu"};
			case "life_inv_oilp": {"oilp"};
			case "life_inv_heroinu": {"heroinu"};
			case "life_inv_heroinp": {"heroinp"};
			case "life_inv_cannabis": {"cannabis"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_apple": {"apple"};
			case "life_inv_water": {"water"};
			case "life_inv_rabbit": {"rabbit"};
			case "life_inv_salema": {"salema"};
			case "life_inv_ornate": {"ornate"};
			case "life_inv_mackerel": {"mackerel"};
			case "life_inv_tuna": {"tuna"};
			case "life_inv_mullet": {"mullet"};
			case "life_inv_catshark": {"catshark"};
			case "life_inv_turtle": {"turtle"};
			case "life_inv_fishingpoles": {"fishing"};
			case "life_inv_coffee": {"coffee"};
			case "life_inv_turtlesoup": {"turtlesoup"};
			case "life_inv_donuts": {"donuts"};
			case "life_inv_fuelE": {"fuelE"};
			case "life_inv_fuelF": {"fuelF"};
			case "life_cash": {"money"};
			case "life_inv_pickaxe": {"pickaxe"};
			case "life_inv_copperore": {"copperore"};
			case "life_inv_ironore": {"ironore"};
			case "life_inv_ironr": {"iron_r"};
			case "life_inv_copperr": {"copper_r"};
			case "life_inv_sand": {"sand"};
			case "life_inv_salt": {"salt"};
			case "life_inv_glass": {"glass"};
			case "life_inv_redgull": {"redgull"};
			case "life_inv_lockpick": {"lockpick"};
			case "life_inv_tbacon": {"tbacon"};
			case "life_inv_peach": {"peach"};
			case "life_inv_diamond": {"diamond"};
			case "life_inv_diamondr": {"diamondc"};
			case "life_inv_saltr": {"salt_r"};
			case "life_inv_coke": {"coke"};
			case "life_inv_cokep": {"cokep"};
			case "life_inv_spikeStrip": {"spikeStrip"};
			case "life_inv_cement": {"cement"};
			case "life_inv_rock": {"rock"};
			case "life_inv_goldbar": {"goldbar"};
			case "life_inv_blastingcharge": {"blastingcharge"};
			case "life_inv_boltcutter": {"boltcutter"};
			case "life_inv_defusekit": {"defusekit"};
			case "life_inv_storagesmall": {"storagesmall"};
			case "life_inv_storagebig": {"storagebig"};
			case "life_inv_battery": {"battery"};
			case "life_inv_barrier": {"barrier"};
			case "life_inv_mauer": {"mauer"};
			case "life_inv_vehiclecharge": {"vehiclecharge"};
			case "life_inv_zipties": {"zipties"};
			case "life_inv_pizza": {"pizza"};
			case "life_inv_bandage": {"bandage"};
			case "life_inv_target": {"target"};
			case "life_inv_bottledwhiskey": {"bottledwhiskey"};
			case "life_inv_bottledbeer": {"bottledbeer"};
			case "life_inv_whiskey": {"whiskey"};
			case "life_inv_beer": {"beer"};
			case "life_inv_stretcher": {"stretcher"};
			case "life_inv_frogs": {"frogs"};
			case "life_inv_lsd": {"lsd"};
			case "life_inv_bigmac": {"bigmac"};
			case "life_inv_fries": {"fries"};
			case "life_inv_blindfold": {"blindfold"};
			case "life_inv_scissors": {"scissors"};
			case "life_inv_spraypaintcamo": {"spraypaintcamo"};
			case "life_inv_spraypaintfunky": {"spraypaintfunky"};
			case "life_inv_spraypaintpink": {"spraypaintpink"};
			case "life_inv_nos": {"nos"};
			case "life_inv_spraypaintzebra": {"spraypaintzebra"};
			case "life_inv_spraypaintcamo2": {"spraypaintcamo2"};
			case "life_inv_turbo": {"turbo"};
			case "life_inv_mp3player": {"mp3player"};
			case "life_inv_autorepairkit": {"autorepairkit"};
			case "life_inv_speedbomb": {"speedbomb"};
			case "life_inv_defibrillator": {"defibrillator"};
			case "life_inv_bullettcamera": {"bullettcamera"};
			case "life_inv_jailpass": {"jailpass"};
			case "life_inv_kidney": {"kidney"};
			case "life_inv_mdma": {"mdma"};
			case "life_inv_ecstasy": {"ecstasy"};
			case "life_inv_masterkey": {"masterkey"};
			case "life_inv_morphine": {"morphine"};
			case "life_inv_epipen": {"epipen"};
			case "life_inv_antifreeze": {"antifreeze"};
			case "life_inv_jailblueprint": {"jailblueprint"};
			case "life_inv_keycard": {"keycard"};
		};
	};
};
